version: '3.3'
services:
  node-film-test-rabbitmq:
     image: lucifer8591/rabbitmq-server:3.7.17
     container_name: node-film-test-rabbitmq
     restart: always
     hostname: node-film-test-rabbitmq
     networks:
       - node-film-test.network
     environment:
       - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
       - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin}
     ports:
       - '4380:4369'
       - '5683:5672'
       - '25683:25672'
       - '15683:15672'

  node-film-test-nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80

  node-film-test-postgres:
    container_name: node-film-test-postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - node-film-test.network
    ports:
      - '5435:5432'
    volumes:
      - ../postgres:/var/lib/postgresql/

  node-film-test-pgadmin:
    container_name: node-film-test-pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - node-film-test.network
    ports:
      - '5050:80'

networks:
  node-film-test.network:
    driver: bridge
